---
apiVersion: v1
kind: Service
metadata:
  name: sysdigcloud-mysql
  labels:
    app: sysdigcloud
    role: mysql-router
spec:
  ports:
  - port: 3306
    targetPort: 6446
  selector:
    app: sysdigcloud
    role: mysql-router
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-mysql-router
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: mysql-router
    spec:
      containers:
        - name: mysql-router
          image: quay.io/sysdig/mysql-router:8.0.11
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: mysql.password
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_HOST
              value: sysdigcloud-mysql-cluster
            - name: MYSQL_INNODB_NUM_MEMBERS
              value: "3"
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
