---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ingress-default-backend
  name: ingress-default-backend
spec:
  selector:
    matchLabels:
      run: ingress-default-backend
  template:
    metadata:
      labels:
        run: ingress-default-backend
    spec:
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      containers:
        - name: ingress-default-backend
          image: quay.io/sysdig/ingress-default-backend:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
