---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-primary
spec:
  serviceName: redis-primary
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-primary
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-primary
        image: quay.io/sysdig/redis:3.2-v12.3
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: sysdigcloud-config
                key: redis.password
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis-primary
        volumeMounts:
        - name: redis-primary-volume
          mountPath: /data
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
  volumeClaimTemplates:
  - metadata:
      name: redis-primary-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: <INSERT_YOUR_STORAGE_CLASS_NAME>
