---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sysdigcloud-elasticsearch
  labels:
    affinity: elasticsearch
    app: sysdigcloud
    component: elasticsearch
    role: elasticsearch
spec:
  updateStrategy:
    type: OnDelete
  serviceName: sysdigcloud-elasticsearch
  podManagementPolicy: Parallel
  # The number of replicas needs to be passed to the pods by ensuring that the value of ELASTICSEARCH_GOSSIP_NODES_NUM
  # matches the number set here.
  replicas: 3
  template:
    metadata:
      labels:
        affinity: elasticsearch
        app: sysdigcloud
        component: elasticsearch
        role: elasticsearch
    spec:
      ## Pod anti-affinity rules ensure that elasticsearch pods run on separate hosts.
      ## You may need to disable these if your number of available kubernetes hosts is less than
      ## the replication factor for your statefulset.
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: affinity
                operator: In
                values:
                - elasticsearch
            topologyKey: kubernetes.io/hostname
      containers:
        - name: elasticsearch
          image: quay.io/sysdig/elasticsearch:5.6.16.7
          securityContext:
            privileged: true
          ## Recommended resource limits for Elasticsearch pods.
          ## Make sure to set values for these limits that are appropriate for your environment.
          #resources:
          #  requests:
          #    cpu: 2
          #    memory: 6Gi
          #  limits:
          #    cpu: 4
          #    memory: 10Gi
          env:
            - name: ELASTICSEARCH_SERVICE
              value: sysdigcloud-elasticsearch
              # ELASTICSEARCH_GOSSIP_NODES_NUM needs to match the number of replicas specified for the statefulset. It will be used to calculate
              # The value of the -Ediscovery.zen.minimum_master_nodes parameter. To override this calculation and set this
              # parameter manually use the DISCOVERY_ZEN_MINIMUM_MASTER_NODES variable.
            - name: ELASTICSEARCH_GOSSIP_NODES_NUM
              value: "3"
            - name: ELASTICSEARCH_CLUSTER_NAME
              value: sysdigcloud
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: elasticsearch.jvm.options
            - name: SEARCHGUARD_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: elasticsearch.searchguard.enabled
            - name: ELASTICSEARCH_USER
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: elasticsearch.user
            ## If enabling elasticsearch auth, uncomment ADMIN_PASSWORD, READONLY_PASSWORD, and READONLY_PASSWORD env var sections
            #- name: ADMIN_PASSWORD
              #valueFrom:
                #secretKeyRef:
                  #name: sg-admin-secret
                  #key: password
            #- name: READONLY_PASSWORD
              #valueFrom:
                #secretKeyRef:
                  #name: sg-readonly-secret
                  #key: password
            #- name: SG_PASSWORD
              #valueFrom:
                #secretKeyRef:
                  #name: sg-admin-secret
                  #key: password
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - /readiness_probe.sh
            initialDelaySeconds: 20
            timeoutSeconds: 5
            failureThreshold: 10
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
            ## If enabling elasticsearch auth, uncomment tool-cert and sg-config volume mounts
            #- mountPath: /tmp/elasticsearch-certs/
              #name: tool-cert
            #- mountPath: /tmp/sgconfig/
              #name: sg-config
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      volumes:
      ## If enabling elasticsearch auth, uncomment tool-cert and sg-config volumes
      #- name: tool-cert
        #secret:
          #secretName: ca-certs
          #defaultMode: 256
      #- name: sg-config
        #secret:
          #secretName: sg-config-files
          #defaultMode: 256
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
        storageClassName: <INSERT_YOUR_STORAGE_CLASS_NAME>
